# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Node.js image with npm
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json /app/package.json

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY src /app/src
COPY tsconfig.json /app/tsconfig.json

# Build the TypeScript code
RUN npm run build

# Use a smaller Node.js image for the release
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the necessary environment variables
ENV NODE_OPTIONS=--experimental-vm-modules

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]
